// One-line subtitle under each page title (PageHeader). Keyed by route name;
// a screen can still pass its own `subtitle` option to override.
export const HEADER_SUBTITLES = {
  EditProfile: 'Update your name, photo and contact details',
  ManageAddress: 'Delivery & pickup addresses',
  AddressForm: 'Where we deliver and pick up',
  ManageDevice: 'Your saved devices',
  CustomerSupport: "We're here to help",
  AboutUs: 'Learn about GGFIX',
  Terms: 'Policies & agreements',
  Faq: 'Answers to common questions',
  MyOrders: 'Track your buy and sell orders',
  RepairOrders: 'Track your service, pickup and enquiry bookings',
  MyCart: 'Items saved for checkout',
  Notifications: 'Updates on your orders and offers',

  CategoryServiceMenu: 'Repair, sell or buy this device',
  SelectCategory: 'Choose your device type',
  SelectBrand: 'Choose your device brand',
  SelectSeries: 'Choose the model series',
  SelectModel: 'Choose your device model',
  SelectVariant: 'Colour, storage and condition',

  RepairSelectDevice: 'Choose the device to repair',
  RepairSelectService: 'Pick the repairs you need',
  RepairReview: 'Check your repair request',
  RepairServiceOptions: 'Walk-in or doorstep pickup',
  RepairPickupShops: 'Choose a shop near you',
  RepairShopDetails: 'Shop info & services',
  RepairSelectAddress: 'Where should we pick up?',
  RepairPickupSlot: 'Choose a pickup date & time',
  RepairCompleteOrder: 'Review and confirm your booking',
  RepairOrderDetails: 'Your repair booking',
  ServiceTicketDetails: 'Your service ticket',
  RepairOrderHistory: 'Status updates for your repair',
  RepairPickupStatus: 'Track your pickup',
  RepairEstimate: "Review the shop's estimate",
  ServiceReceipt: 'Your service receipt',
  InvoiceReceipt: 'Your repair invoice',

  ShopChat: 'Chat with the shop',
  ChatInbox: 'Your conversations with shops',

  SellSelectDevice: 'Choose the device to sell',
  SellCondition: 'Device details for your sale',
  SellScreening: 'A few quick questions',
  SellScreenCondition: 'Screen and body condition',
  SellFunctional: 'Select any issues',
  SellDeviceConfig: 'Tell us about the device',
  SellAccessoriesWarranty: 'Accessories and warranty',
  SellImages: 'Add photos of your device',
  SellAddress: 'Where should we pick up?',
  SellComplete: 'Review and submit your sale',
  SellOrderDetails: 'Your sell request',
  SellQuotation: 'Quotes from verified shops',
  SellSelectShop: 'Pick the quote you want',

  BuyCategory: 'Brands, prices and more',
  BuyListing: 'Devices available near you',
  BuyProductDetails: 'Product info & seller',
  NearbyShops: 'Repair shops around you',
  ShopDetails: 'Shop info & services',
};
